name: Release

on:
  push:
    branches: ["main"]

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    env:
      APPNAME: ZA-Trainer-Editor

    steps:
      - uses: actions/checkout@v3

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Set up just
        uses: extractions/setup-just@v2

      - name: Install dependencies and test
        run: |
          just prepare
          just install

      - name: Build app
        run: |
          just build-app ${APPNAME}

      - name: Zip dist folder
        run: |
          cd dist/
          zip -r ${APPNAME}.zip ${APPNAME}.app

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: uv run python -c "import skypy; print(skypy.__version__)"
          release_name: uv run python -c "import skypy; print(skypy.__version__)"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload App
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/${APPNAME}.zip
          asset_name: ${APPNAME}
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ github.token }}
